
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    exposer: Ingress
    http: true
    tlsacme: false

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

  ## Values from here can be customized https://github.com/helm/charts/blob/master/stable/mongodb/values.yaml


## if we manipulate the Makefile to use the requirments from the main chart, the conditions are under key nuxeo

nuxeo:
  kafka:
    deploy: false 
  postgresql:
    deploy: false
  mongodb:
    deploy: true 
  elasticsearch:
    deploy: true        


preview:
  mongodb:
    usePassword: false
  image:
    repository:
    tag:
    pullPolicy: IfNotPresent
     
 
