
dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- name: mongodb
  version: 4.0.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: nuxeo.mongodb.deploy
  alias: mongodb
